app:
  db:
    src: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: root
spring:
  datasource:
    url: ${app.db.src}
    username: ${app.db.username}
    password: ${app.db.password}
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: spring
      password: guru
  jpa:
    hibernate:
      default_schema: public
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      root: DEBUG
      org:
        springframework:
          security: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql: DEBUG
  flyway:
    url: ${app.db.src}
    user: ${app.db.username}
    password: ${app.db.password}
    locations:
      classpath: db/migration
