CREATE TABLE USER_ACCOUNT (
    USER_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_LOGIN TIMESTAMP,
    ROLE VARCHAR(50),
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE CATEGORY (
    CATEGORY_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(64) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT,
    FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID) ON DELETE CASCADE
);

CREATE TABLE BUDGET (
    BUDGET_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(64) NOT NULL,
    CATEGORY_ID VARCHAR(64) NOT NULL,
    AMOUNT DOUBLE PRECISION NOT NULL,
    MONTH INT NOT NULL,
    YEAR INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES category(CATEGORY_ID) ON DELETE CASCADE
);

CREATE TABLE REPORT (
    REPORT_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(64) NOT NULL,
    REPORT_TYPE VARCHAR(255) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    GENERATED_DATE DATE NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID) ON DELETE CASCADE
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(64) NOT NULL,
    CATEGORY_ID VARCHAR(64) NOT NULL,
    AMOUNT DOUBLE PRECISION NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    DATE DATE NOT NULL,
    DESCRIPTION TEXT,
    FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES category(CATEGORY_ID) ON DELETE CASCADE
);
