CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USER_ACCOUNT (
    USER_ID UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_LOGIN TIMESTAMP,
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE CATEGORY (
    CATEGORY_ID UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE BUDGET (
    BUDGET_ID UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    USER_ID UUID NOT NULL,
    AMOUNT DOUBLE PRECISION NOT NULL,
    MONTH INT NOT NULL,
    YEAR INT NOT NULL,
    CONSTRAINT fk_user_account FOREIGN KEY (USER_ID) REFERENCES user_account(USER_ID)
);

CREATE TABLE BUDGET_CATEGORY (
    BUDGET_ID UUID NOT NULL,
    CATEGORY_ID UUID NOT NULL,
    PRIMARY KEY (BUDGET_ID, CATEGORY_ID),
    CONSTRAINT fk_budget FOREIGN KEY (BUDGET_ID) REFERENCES budget(BUDGET_ID),
    CONSTRAINT fk_category FOREIGN KEY (CATEGORY_ID) REFERENCES category(CATEGORY_ID)
);

CREATE TABLE REPORT (
    REPORT_ID UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    USER_ID UUID NOT NULL,
    REPORT_TYPE VARCHAR(255) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    GENERATED_DATE DATE NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES user_account(USER_ID)
);

CREATE TABLE ROLE (
    ROLE_ID UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    ROLE VARCHAR(50) NOT NULL
);

CREATE TABLE USER_ACCOUNT_ROLE (
    USER_ID UUID NOT NULL,
    ROLE_ID UUID NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT fk_user_account_role_user_account
        FOREIGN KEY (USER_ID)
            REFERENCES USER_ACCOUNT (USER_ID),
    CONSTRAINT fk_user_account_role_role
        FOREIGN KEY (ROLE_ID)
            REFERENCES ROLE (ROLE_ID)
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    USER_ID UUID NOT NULL,
    CATEGORY_ID UUID NOT NULL,
    AMOUNT DOUBLE PRECISION NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    DATE DATE NOT NULL,
    DESCRIPTION TEXT,
    FOREIGN KEY (USER_ID) REFERENCES user_account(USER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES category(CATEGORY_ID)
);
