INSERT INTO USER_ACCOUNT (USER_ID, LOGIN, PASSWORD, EMAIL, CREATED_DATE, LAST_LOGIN, ROLE, DELETED, ACTIVE) VALUES
-- password : password1
(uuid_generate_v4(), 'user1', '$2a$16$xcGZYMOGay5xGVL2p3.vV.6mH4KCIgTKtKERz/M/rdRrNPM7EVR2S', 'user1@example.com', NOW(), NOW(), 'ADMINISTRATOR::USER', FALSE, TRUE),
(uuid_generate_v4(), 'user2', '$2a$16$xcGZYMOGay5xGVL2p3.vV.6mH4KCIgTKtKERz/M/rdRrNPM7EVR2S', 'user2@example.com', NOW(), NOW(), 'USER', FALSE, TRUE),
(uuid_generate_v4(), 'user3', '$2a$16$xcGZYMOGay5xGVL2p3.vV.6mH4KCIgTKtKERz/M/rdRrNPM7EVR2S', 'user3@example.com', NOW(), NOW(), 'USER', FALSE, TRUE),
(uuid_generate_v4(), 'user4', '$2a$16$xcGZYMOGay5xGVL2p3.vV.6mH4KCIgTKtKERz/M/rdRrNPM7EVR2S', 'user4@example.com', NOW(), NOW(), 'USER', FALSE, TRUE),
(uuid_generate_v4(), 'user5', '$2a$16$xcGZYMOGay5xGVL2p3.vV.6mH4KCIgTKtKERz/M/rdRrNPM7EVR2S', 'user5@example.com', NOW(), NOW(), 'USER', FALSE, TRUE);

INSERT INTO CATEGORY (CATEGORY_ID, USER_ID, NAME, TYPE, DESCRIPTION) VALUES
(uuid_generate_v4(), (SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user1'), 'Groceries', 'EXPENSE', 'Weekly food and supplies'),
(uuid_generate_v4(), (SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user1'), 'Salary', 'INCOME', 'Monthly salary'),
(uuid_generate_v4(), (SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user1'), 'Utilities', 'EXPENSE', 'Monthly bills for utilities'),
(uuid_generate_v4(), (SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user1'), 'Investments', 'INCOME', 'Investment returns'),
(uuid_generate_v4(), (SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user1'), 'Entertainment', 'EXPENSE', 'Expenses for entertainment');

INSERT INTO BUDGET (USER_ID, CATEGORY_ID, AMOUNT, MONTH, YEAR) VALUES
((SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user1'), (SELECT CATEGORY_ID FROM CATEGORY WHERE NAME = 'Groceries'), 500.00, 9, 2023),
((SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user2'), (SELECT CATEGORY_ID FROM CATEGORY WHERE NAME = 'Salary'), 1500.00, 9, 2023),
((SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user3'), (SELECT CATEGORY_ID FROM CATEGORY WHERE NAME = 'Utilities'), 750.00, 9, 2023),
((SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user4'), (SELECT CATEGORY_ID FROM CATEGORY WHERE NAME = 'Investments'), 1000.00, 9, 2023),
((SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user5'), (SELECT CATEGORY_ID FROM CATEGORY WHERE NAME = 'Entertainment'), 600.00, 9, 2023);

INSERT INTO TRANSACTIONS (USER_ID, CATEGORY_ID, AMOUNT, TYPE, DATE, DESCRIPTION) VALUES
((SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user1'), (SELECT CATEGORY_ID FROM CATEGORY WHERE NAME = 'Groceries'), 150.50, 'EXPENSE', '2023-09-01', 'Grocery shopping'),
((SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user2'), (SELECT CATEGORY_ID FROM CATEGORY WHERE NAME = 'Salary'), 2000.00, 'INCOME', '2023-09-05', 'Received salary');

INSERT INTO REPORT (REPORT_ID, USER_ID, REPORT_TYPE, START_DATE, END_DATE, GENERATED_DATE) VALUES
(uuid_generate_v4(), (SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user1'), 'Monthly Expense Report', '2023-09-01', '2023-09-30', NOW()),
(uuid_generate_v4(), (SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user2'), 'Annual Income Report', '2023-01-01', '2023-12-31', NOW()),
(uuid_generate_v4(), (SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user3'), 'Quarterly Savings Report', '2023-07-01', '2023-09-30', NOW()),
(uuid_generate_v4(), (SELECT USER_ID FROM USER_ACCOUNT WHERE LOGIN = 'user4'), 'Investment Performance Report', '2023-01-01', '2023-12-31', NOW());
